[package]
name = "auto-slowmode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
poise = "0.5.6"
serenity = "0.11.6"
tokio = { version = "1.33.0", features = ["full"] }
